### ISSUE TITLE
please publish to npm

### ISSUE THREAD

**Issue by stevenvachon** [orangemug/classlist-toggle-force-polyfill#1]

**Comment by stevenvachon** [comment]
Never mind, I found https://github.com/eligrey/classList.js/ which also adds multiple argument support to `.add()` and `.remove()`.

**Comment by orangemug** [comment]
@stevenvachon sorry I completely missed this, for reference you can also install with

```
npm install orangemug/classlist-toggle-force-polyfill
```

**Comment by stevenvachon** [comment]
No problem -- I ended up using [classlist.js](https://www.npmjs.com/package/classlist.js).
